/// <reference types="node" />
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
  
});

//why is node on types = giving me an error in this file?
// why is that .env without process.env giving me an error in this file? yet on the folder structure .env file is present and not inside process.env?
// The error is likely because the TypeScript compiler cannot find the type definitions for Node.js. To fix this, you can install the @types/node package as a development dependency in your project. You can do this by running the following command in your terminal:

// npm install --save-dev @types/node

